apiVersion: field.vmware.com/v1
kind: ArgoNamespace
metadata:
  name: sample-ns
spec:
  argoNamespace: "argocd"
  serviceAccount: "testing-account"
  clusterLabels:
    test: "test"
  project: default