apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argoclusters.field.vmware.com
spec:
  group: field.vmware.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
                argoNamespace:
                  type: string
                project:
                  type: string
                  description: the argo project to attach to
                clusterLabels:
                  type: object
                  description: map of keys/values that are added to the labels in argocd for the cluster
                  additionalProperties: true
              required:
                - clusterName
                - argoNamespace
                - project
            status: 
              type: object
              description: Current status of the Argonamespace.
              x-kubernetes-preserve-unknown-fields: true 
              properties:
                state:
                  type: string
                message:
                  type: string
                ready:
                  type: boolean
                lastUpdated:
                  type: string
                  format: date-time
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: argoclusters
    singular: argocluster
    kind: ArgoCluster
    shortNames:
      - argcl
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argonamespaces.field.vmware.com
spec:
  group: field.vmware.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                argoNamespace:
                  type: string
                  description: the namespace that the ArgoCD instance is deployed into
                serviceAccount:
                  type: string
                  description: an existing service account to use for the namespace attachment
                project:
                  type: string
                  description: the argo project to attach to
                clusterLabels:
                  type: object
                  description: map of keys/values that are added to the labels in argocd for the cluster
                  additionalProperties: true
              required:
                - argoNamespace
                - project
            status: 
              type: object
              description: Current status of the Argonamespace.
              x-kubernetes-preserve-unknown-fields: true 
              properties:
                state:
                  type: string
                message:
                  type: string
                ready:
                  type: boolean
                lastUpdated:
                  type: string
                  format: date-time
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: argonamespaces
    singular: argonamespace
    kind: ArgoNamespace
    shortNames:
      - argns